// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4odg9qcU4Q1sHCiIakfuxXIIUAz8RqY0',
    appId: '1:993436139055:web:e0f9481403287d46dd50da',
    messagingSenderId: '993436139055',
    projectId: 'technicalservices-2973a',
    authDomain: 'technicalservices-2973a.firebaseapp.com',
    databaseURL: 'https://technicalservices-2973a-default-rtdb.firebaseio.com',
    storageBucket: 'technicalservices-2973a.appspot.com',
    measurementId: 'G-DSVM7DCTB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQWODC5gAmxRpEUrjoNw9wBjeBdMNi3UU',
    appId: '1:993436139055:android:72aa5328d6736456dd50da',
    messagingSenderId: '993436139055',
    projectId: 'technicalservices-2973a',
    databaseURL: 'https://technicalservices-2973a-default-rtdb.firebaseio.com',
    storageBucket: 'technicalservices-2973a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGXu_04HThO4Jl8OzznAgoXu-qzX7gkOE',
    appId: '1:993436139055:ios:b1803394f4022ed4dd50da',
    messagingSenderId: '993436139055',
    projectId: 'technicalservices-2973a',
    databaseURL: 'https://technicalservices-2973a-default-rtdb.firebaseio.com',
    storageBucket: 'technicalservices-2973a.appspot.com',
    androidClientId: '993436139055-23n0kral5nen08k97u32s52rukf1i0bc.apps.googleusercontent.com',
    iosClientId: '993436139055-0qlh731n8pechu9ls0h8em0bvfai58f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.technicalserviceadmin',
  );
}
